import{S as l,i as d}from"./assets/vendor-7659544d.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function u(t){const r=`https://pixabay.com/api/?key=42262858-7b31826aafbc45fb5436f2ee9&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await fetch(r);if(!n.ok)throw new Error("An error occurred while making the request.");const e=await n.json();e.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):m(e.hits)}catch(n){console.error("Error:",n.message),c(`Error fetching images: ${n}`)}}function m(t){const o=document.getElementById("gallery");o.innerHTML="";for(let n=0;n<Math.min(t.length,15);n++){const e=p(t[n]);o.appendChild(e)}new l(".gallery a").refresh()}function p(t){const o=document.createElement("div");o.classList.add("card");const r=document.createElement("img");r.src=t.webformatURL,r.alt=t.tags;const n=document.createElement("div");n.classList.add("overlay");const e=document.createElement("div");return e.classList.add("details"),e.innerHTML=`
        <p>Likes: ${t.likes}</p>
        <p>Views: ${t.views}</p>
        <p>Comments: ${t.comments}</p>
        <p>Downloads: ${t.downloads}</p>
    `,n.appendChild(e),o.appendChild(r),o.appendChild(n),o.addEventListener("click",()=>f(t.largeImageURL,t.tags)),o}function f(t,o){const r=document.createElement("div");r.classList.add("modal"),r.innerHTML=`
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <img src="${t}" alt="${o}">
        </div>
    `,document.body.appendChild(r),r.querySelector(".close-modal").addEventListener("click",()=>{i(r)}),document.addEventListener("keydown",e=>{e.key==="Escape"&&i(r)})}function i(t){document.body.removeChild(t)}function c(t){d.error({title:"Error",message:t,backgroundColor:"#EF4040",progressBarColor:"#FFE0AC",icon:"icon-close",position:"topRight",displayMode:"replace",closeOnEscape:!0,pauseOnHover:!1,maxWidth:432,messageSize:"16px",messageLineHeight:"24px"})}function h(){document.querySelector(".search-form").addEventListener("submit",function(o){o.preventDefault();const r=o.target.elements.query.value.trim();if(r===""){c("Please enter a search query.");return}u(r)})}document.addEventListener("DOMContentLoaded",function(){h()});
//# sourceMappingURL=commonHelpers.js.map
