import{i as a,S as i}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function l(r){try{await d(r)}catch(t){console.error("Error performing search:",t.message)}}async function d(r){const o=`https://pixabay.com/api/?key=42262858-7b31826aafbc45fb5436f2ee9&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await fetch(o);if(!n.ok)throw new Error("An error occurred while making the request.");const e=await n.json();e.hits.length===0?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):u(e.hits)}catch(n){throw console.error("Error:",n.message),n}}function u(r){const t=document.getElementById("gallery");t.innerHTML="",r.forEach(o=>{const n=m(o);t.appendChild(n)}),y.refresh()}function m(r){const t=document.createElement("div");t.classList.add("card");const o=document.createElement("img");o.src=r.webformatURL,o.alt=r.tags;const n=document.createElement("div");n.classList.add("overlay");const e=document.createElement("div");return e.classList.add("details"),e.innerHTML=`
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
    `,n.appendChild(e),t.appendChild(o),t.appendChild(n),t.addEventListener("click",()=>p(r.largeImageURL,r.tags)),t}function p(r,t){const o=document.createElement("div");o.classList.add("modal"),o.innerHTML=`
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <img src="${r}" alt="${t}">
        </div>
    `,document.body.appendChild(o),o.querySelector(".close-modal").addEventListener("click",()=>{document.body.removeChild(o)})}const f=document.querySelector(".search-form"),h=document.querySelector(".image-query");f.addEventListener("submit",function(r){r.preventDefault();const t=h.value.trim();if(t===""){a.show({title:"Error",message:"Please enter a search query.",backgroundColor:"#ff0000",timeout:5e3});return}l(t)});const y=new i(".gallery a");
//# sourceMappingURL=commonHelpers.js.map
